---

pepyatka_html_repo: https://github.com/pepyatka/pepyatka-html.git
pepyatka_html_branch: development
www_user: www-data
www_group: www-data
pepyatka_hostname: localhost
pepyatka_server_host: localhost
pepyatka_server_instances:
  - 3000
pepyatka_frontend_scheme: http
pepyatka_files_dir: /var/pepyatka-files
pepyatka_s3_bucket: ""
nginx_client_max_body_size: '10M'
nginx_use_proxy_protocol: False
nginx_proxy_protocol_real_ips: []
pepyatka_ga_account: "UA-XXXXXX"
pepyatka_lite_enabled: False
freefeed_react_client_enabled: False
freefeed_react_client_repo: https://github.com/freefeed/freefeed-react-client.git
freefeed_react_client_branch: master

