---

pepyatka_user: pepyatka
pepyatka_group: pepyatka
pepyatka_service_name: Pepyatka
pepyatka_server_repo: https://github.com/pepyatka/pepyatka-server.git
pepyatka_server_branch: development
pepyatka_server_instances:
  - 3000
pepyatka_hostname: localhost
pepyatka_origin: '*'
pepyatka_home_dir: /opt/pepyatka
pepyatka_storage_type: fs
pepyatka_files_dir: /var/pepyatka-files
pepyatka_aws_access_key: "null" # Use "'value'" for non-nulls
pepyatka_aws_secret_key: "null" # Use "'value'" for non-nulls
pepyatka_s3_bucket: ""
pepyatka_file_size_limit: '10mb'
pepyatka_node_env: development
pepyatka_secret: 'secret'
pepyatka_redis_host: 'localhost'
pepyatka_redis_port: 6379
pepyatka_frontend_scheme: http
pepyatka_mailer_smtp_enabled: False
pepyatka_mailer_smtp_secure: 'false'
pepyatka_mailer_smtp_host: localhost
pepyatka_mailer_smtp_port: 25
pepyatka_mailer_smtp_user: 'username'
pepyatka_mailer_smtp_pass: 'password'
pepyatka_mailer_from_name: 'Pepyatka'
pepyatka_mailer_from_email: 'mail@pepyatka.com'
pepyatka_accept_hashed_passwords_only: 'false'
pepyatka_banlist: ""
freefeed_recaptcha_enabled: false
freefeed_recaptcha_secret: ""
