---

- pre_tasks:
  hosts: all
  connection: local
  gather_facts: False
  become: False
  tasks:
    - name: Delete saved changelogs
      file: path="playbooks/{{ item }}" state=absent
      with_items:
        - pepyatka-server-changelog
        - pepyatka-html-changelog
        - pepyatka-lite-changelog
        - freefeed-react-client-changelog
      when: slack_token is defined
      tags:
        - changelog

- include: elasticsearch.yml
- include: redis.yml
- include: postgres.yml
- include: pepyatka.yml
- include: nginx.yml

- post_tasks:
  hosts: all
  connection: local
  gather_facts: False
  become: False
  tasks:
    - name: Send pepyatka-server changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated pepyatka-server on {{ item | basename }}. <{{ pepyatka_server_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-server-changelog/*
      when: slack_token is defined
      tags:
        - changelog

    - name: Send pepyatka-html changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated pepyatka-html on {{ item | basename }}. <{{ pepyatka_html_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-html-changelog/*
      when: slack_token is defined and pepyatka_html_enabled
      tags:
        - changelog

    - name: Send pepyatka-lite changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated pepyatka-lite on {{ item | basename }}. <{{ pepyatka_lite_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - pepyatka-lite-changelog/*
      when: slack_token is defined and pepyatka_lite_enabled
      tags:
        - changelog

    - name: Send freefeed-react-client changelog to Slack
      local_action:
        module: slack
        token: "{{ slack_token }}"
        msg: "Updated freefeed-react-client on {{ item | basename }}. <{{ freefeed_react_client_repo | replace('.git', '')}}/compare/{{ lookup('file', item) }}|Changelog>"
      with_fileglob:
        - freefeed-react-client-changelog/*
      when: slack_token is defined and freefeed_react_client_enabled
      tags:
        - changelog


